language: node_js
node_js:
  - "lts/boron"
cache:
  directories:
    - "node_modules"
before_install:
#skip_cleanup: true
deploy:
  provider: npm
  email: geert.premereur+github@ictects.com
  api_key: $NPM_TOKEN
  on:
    tags: true
